import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vincular",
  description: "Generated by create next app",
  icons :{
    icon : "https://c8.alamy.com/comp/KXTR9F/letter-v-handwritten-by-dry-brush-rough-strokes-font-vector-illustration-KXTR9F.jpg"
  }

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      
      >
        {children}
      </body>
    </html>
  );
}


